### ISSUE TITLE
Are you open to LinkedIn invites from ACU Alum? If so, which email addy?

### ISSUE THREAD

**Issue by eddodds** [nxw13a/NEXTLAB_REG#1]

**Comment by nxw13a** [comment]
My email: nxw13a@acu.edu
My LinkedIn: https://www.linkedin.com/in/nattapat-white-99151a11b
Yes, I am open to ACU Alumni.

**Comment by fab16b** [comment]
Yes, I am definitely open for it. You can add me, please.
My email: mbikogbiafelix@gmail.com /  fab16b@acu.edu (my school email)
My linkedIn: linkedin.com/in/felix-mbikogbia-90660b11b
